# Generated by Django 4.1.5 on 2023-01-26 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userregmodel',
        ),
    ]
