# Generated by Django 4.1.5 on 2023-01-26 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0003_shopregmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shopregmodel',
        ),
    ]
