# Generated by Django 4.1.5 on 2023-01-29 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0008_wishlistmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productmodel',
        ),
        migrations.DeleteModel(
            name='regmodel',
        ),
        migrations.DeleteModel(
            name='wishlistmodel',
        ),
    ]
