# Generated by Django 4.1.5 on 2023-02-01 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0011_cartmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='buymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
