# Generated by Django 4.1.5 on 2023-02-05 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0014_alter_paymentmodel_fname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='paymentmodel',
        ),
    ]
