# Generated by Django 4.1.5 on 2023-02-07 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0017_delete_buymodel_regmodel_uid_wishlistmodel_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regmodel',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='wishlistmodel',
            name='uid',
        ),
    ]
