# Generated by Django 4.1.5 on 2023-02-08 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0018_remove_regmodel_uid_remove_wishlistmodel_uid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='paymentmodel',
        ),
    ]
