# Generated by Django 4.1.5 on 2023-02-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0021_wishlistmodel_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodel',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
